(() => {
  const chatKey = 'ideal-machine-chat';
  const storageKey = 'ideal-machine-couple';
  const app = document.createElement('div');
  app.className = 'couple-app';
  app.innerHTML = '<div class="couple-page"></div><input class="couple-hidden-file" type="file" accept="image/*">';
  document.body.appendChild(app);
  let tab = 'home';
  let recordType = '';
  let openLetterId = '';

  const esc = value => String(value || '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
  const uid = prefix => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;
  const readChat = () => { try { const value = JSON.parse(localStorage.getItem(chatKey) || '{}'); return { contacts: Array.isArray(value.contacts) ? value.contacts : [], profiles: Array.isArray(value.profiles) ? value.profiles : [], chats: value.chats || {} }; } catch { return { contacts: [], profiles: [], chats: {} }; } };
  const read = () => { try { const value = JSON.parse(localStorage.getItem(storageKey) || '{}'); return { contactId: value.contactId || '', memories: Array.isArray(value.memories) ? value.memories : [], moods: value.moods || {}, moodReply: value.moodReply || '', wishes: Array.isArray(value.wishes) ? value.wishes : [], wishReplies: value.wishReplies || {}, letters: Array.isArray(value.letters) ? value.letters : [], letterReplies: value.letterReplies || {}, events: Array.isArray(value.events) ? value.events : [], answers: value.answers || {}, roleAnswers: value.roleAnswers || {}, roleNotes: value.roleNotes || {}, dailyQuestionDate: value.dailyQuestionDate || '', dailyQuestionText: value.dailyQuestionText || '', interaction: value.interaction || '', interactionReply: value.interactionReply || '' }; } catch { return { contactId: '', memories: [], moods: {}, moodReply: '', wishes: [], wishReplies: {}, letters: [], letterReplies: {}, events: [], answers: {}, roleAnswers: {}, roleNotes: {}, dailyQuestionDate: '', dailyQuestionText: '', interaction: '', interactionReply: '' }; } };
  let state = read();
  try { localStorage.setItem('ideal-machine-calendar-events', JSON.stringify(state.events || [])); } catch {}
  let pendingMemory = null;
  let apiBusy = false;
  const save = () => { localStorage.setItem(storageKey, JSON.stringify(state)); localStorage.setItem('ideal-machine-calendar-events', JSON.stringify(state.events || [])); window.IdealMachineRenderCalendar?.(); };
  const chatData = () => readChat();
  const current = () => { const data = chatData(); const role = data.contacts.find(item => item.id === state.contactId) || data.contacts[0]; const profileId = role ? data.chats[role.id]?.profileId : ''; const profile = data.profiles.find(item => item.id === profileId); if (role && state.contactId !== role.id) { state.contactId = role.id; save(); } return { data, role, profile }; };
  const avatar = (item, fallback = '♡') => item?.avatar ? `<img src="${esc(item.avatar)}" alt="">` : `<span>${esc((item?.nickname || item?.name || fallback).slice(0, 1))}</span>`;
  const roleName = role => role?.nickname || role?.name || '角色';
  const profileName = profile => profile?.nickname || profile?.realName || profile?.name || '我';
  const date = () => new Date().toLocaleDateString('zh-CN', { year:'numeric', month:'long', day:'numeric' });
  const questions = ['今天最想和对方一起做什么？', '最近哪一个瞬间让你想起对方？', '如果现在可以见面，你会先说什么？', '你们下一次约会想去哪里？'];

  function tabIcon(type) { const paths = { home:'<path d="m8 22 16-13 16 13v16a3 3 0 0 1-3 3H11a3 3 0 0 1-3-3z"/><path d="M19 41V28h10v13"/>', calendar:'<rect x="8" y="10" width="32" height="30" rx="4"/><path d="M15 7v7M33 7v7M8 19h32"/>', memories:'<rect x="8" y="10" width="32" height="29" rx="4"/><circle cx="18" cy="20" r="3"/><path d="m10 34 9-9 6 6 5-5 8 8"/>', wishes:'<path d="m24 39-14-13a9 9 0 0 1 13-13l1 1 1-1a9 9 0 0 1 13 13z"/>', mailbox:'<rect x="7" y="11" width="34" height="27" rx="4"/><path d="m9 14 15 12 15-12"/>' }; return `<svg class="couple-tab-icon" viewBox="0 0 48 48" aria-hidden="true">${paths[type]}</svg>`; }
  function render() {
    const page = app.querySelector('.couple-page');
    const { data, role, profile } = current();
    const compactHeader = tab !== 'home';
    const subPage = ['questions', 'mood', 'interaction'].includes(tab);
    const pageTitle = tab === 'questions' ? '每日问题' : tab === 'mood' ? '今日心情' : '轻轻互动';
    const subHeader = tab === 'questions' ? '<span>DAILY QUESTION</span><h1>每日问题</h1>' : tab === 'mood' ? '<span>DAILY MOOD</span><h1>今日心情</h1>' : tab === 'interaction' ? '<span>SMALL MOMENT</span><h1>轻轻互动</h1>' : tab === 'calendar' ? '<span>TOGETHER</span><h1>共同日历</h1>' : tab === 'memories' ? '<span>MEMORIES</span><h1>回忆相册</h1>' : tab === 'wishes' ? '<span>OUR PLANS</span><h1>共同愿望</h1>' : '<span>PRIVATE LETTERS</span><h1>情侣信箱</h1>';
    page.innerHTML = `<header class="couple-header ${compactHeader ? 'is-subpage' : ''}"><div>${compactHeader ? subHeader : '<span>PRIVATE SPACE</span><h1>情侣空间</h1>'}</div><button data-couple-${compactHeader ? 'home' : 'close'} type="button">×</button></header><main class="couple-main">${tab === 'home' ? home(role, profile) : tab === 'calendar' ? calendar() : tab === 'memories' ? memories() : tab === 'wishes' ? wishes() : tab === 'mailbox' ? mailbox() : tab === 'mood' ? moodPage(role) : tab === 'interaction' ? interactionPage(role) : questionsPage(role, profile)}</main>${subPage ? '' : `<nav class="couple-tabs"><button data-couple-tab="home" class="${tab === 'home' ? 'is-active' : ''}" type="button">${tabIcon('home')}<small>首页</small></button><button data-couple-tab="calendar" class="${tab === 'calendar' ? 'is-active' : ''}" type="button">${tabIcon('calendar')}<small>日历</small></button><button data-couple-tab="memories" class="${tab === 'memories' ? 'is-active' : ''}" type="button">${tabIcon('memories')}<small>回忆</small></button><button data-couple-tab="wishes" class="${tab === 'wishes' ? 'is-active' : ''}" type="button">${tabIcon('wishes')}<small>愿望</small></button><button data-couple-tab="mailbox" class="${tab === 'mailbox' ? 'is-active' : ''}" type="button">${tabIcon('mailbox')}<small>信箱</small></button></nav>`}${recordOpenMarkup()}${letterOpenMarkup()}`;
  }
  function home(role, profile) {
    const mood = state.moods.user || '还没有记录';
    return `<section class="couple-hero"><div class="couple-hero-avatar">${avatar(role)}</div><div class="couple-heart">♡</div><div class="couple-hero-avatar">${avatar(profile, 'U')}</div><h2>${esc(roleName(role))} & ${esc(profileName(profile))}</h2><p>${profile ? `用户已自动绑定：${esc(profileName(profile))}` : '请先在聊天设置中绑定用户设定'}</p></section><section class="couple-home-grid"><button data-couple-action="mood" type="button"><b>今日心情</b><strong>${esc(mood)}</strong><small>记录一下今天</small></button><button data-couple-tab="questions" type="button"><b>每日问题</b><strong>今天想和你一起做什么？</strong><small>写下你的答案</small></button><button data-couple-action="interact" type="button"><b>轻轻互动</b><strong>${esc(state.interaction || '想你了')}</strong><small>给对方一个回应</small></button><button data-couple-tab="calendar" type="button"><b>共同日历</b><strong>${state.events.length ? `${state.events.length} 个记录` : '还没有纪念日'}</strong><small>记住值得纪念的日子</small></button></section><section class="couple-feature-card"><span>OUR SPACE</span><h2>把日常写成只属于你们的故事。</h2><p>记录心情、收集回忆，也为下一次见面留一盏灯。</p><button data-couple-role-picker type="button">更换角色</button></section>`;
  }
  function moodPage(role) { const choices = ['开心', '平静', '想念', '有点累', '期待见面']; return `<p class="couple-subhint">选择一种心情，${esc(roleName(role))} 会通过 API 回应你。</p><div class="couple-choice-list">${choices.map(item => `<button class="couple-choice ${state.moods.user === item ? 'is-selected' : ''}" data-couple-mood="${esc(item)}" type="button" ${apiBusy ? 'disabled' : ''}><span>${esc(item)}</span><i>${state.moods.user === item ? '✓' : '○'}</i></button>`).join('')}</div>${apiBusy ? '<p class="couple-api-status">角色正在回应…</p>' : ''}${state.moodReply ? `<div class="couple-response"><span>${esc(roleName(role))}</span><p>${esc(state.moodReply)}</p></div>` : ''}`; }
  function interactionPage(role) { const choices = ['想你了', '抱抱我', '晚安', '亲亲', '陪我一会儿']; return `<p class="couple-subhint">选一个互动，${esc(roleName(role))} 会通过 API 回应你。</p><div class="couple-choice-list">${choices.map(item => `<button class="couple-choice ${state.interaction === item ? 'is-selected' : ''}" data-couple-interaction="${esc(item)}" type="button" ${apiBusy ? 'disabled' : ''}><span>${esc(item)}</span><i>${state.interaction === item ? '✓' : '○'}</i></button>`).join('')}</div>${apiBusy ? '<p class="couple-api-status">角色正在回应…</p>' : ''}${state.interactionReply ? `<div class="couple-response"><span>${esc(roleName(role))}</span><p>${esc(state.interactionReply)}</p></div>` : ''}`; }
  function roleNote(type) { return state.roleNotes?.[type] ? `<div class="couple-response"><span>角色回应</span><p>${esc(state.roleNotes[type])}</p></div>` : ''; }
  function calendar() { return `<p class="couple-subhint">把纪念日同步到日历 App，也可以让角色替你添加。</p><div class="couple-action-row"><button class="couple-primary" data-couple-add-event type="button">用户添加</button><button class="couple-secondary" data-couple-role-add-event type="button">角色添加</button></div><div class="couple-list">${state.events.length ? state.events.map(item => `<article class="couple-list-card"><div><b>${esc(item.title)}</b><small>${esc(item.date)} · ${item.author === 'role' ? '角色添加' : '用户添加'}</small></div><button data-couple-delete-event="${esc(item.id)}" type="button">×</button></article>`).join('') : '<p class="couple-empty">还没有纪念日记录。</p>'}</div>`; }
  function memories() { return `<p class="couple-subhint">保存一起经历过的片段。</p><button class="couple-primary" data-couple-add-memory type="button">记录一段回忆</button><div class="couple-memory-list">${state.memories.length ? state.memories.map(item => `<article class="couple-memory-card">${item.image ? `<img src="${esc(item.image)}" alt="">` : ''}<div><b>${esc(item.title)}</b><small>${esc(item.date)}</small><p>${esc(item.text)}</p></div></article>`).join('') : '<p class="couple-empty">还没有回忆，记录你们的第一段故事吧。</p>'}</div><button class="couple-secondary" data-couple-role-response="memories" type="button">让角色看看回忆</button>${roleNote('memories')}`; }
  function wishes() { return `<p class="couple-subhint">把想一起完成的事情放在这里，完成时会留下角色的回应。</p><button class="couple-primary" data-couple-add-wish type="button">添加共同愿望</button><div class="couple-list">${state.wishes.length ? state.wishes.map(item => `<div class="couple-wish-wrap"><button class="couple-wish ${item.done ? 'is-done' : ''}" data-couple-toggle-wish="${esc(item.id)}" type="button"><i>${item.done ? '✓' : '○'}</i><span>${esc(item.text)}<small>${item.done ? '已完成' : '想去完成'}</small></span></button>${state.wishReplies?.[item.id] ? `<div class="couple-wish-reply"><b>角色</b><p>${esc(state.wishReplies[item.id])}</p></div>` : ''}</div>`).join('') : '<p class="couple-empty">还没有共同愿望。</p>'}</div>`; }
  function mailbox() { return `<p class="couple-subhint">写一封给未来的信，每封信都可以收到独立回信。</p><button class="couple-primary" data-couple-add-letter type="button">写一封信</button><div class="couple-list">${state.letters.length ? state.letters.map(item => `<button class="couple-letter" data-couple-letter="${esc(item.id)}" type="button"><b>${esc(item.title)}</b><small>${esc(item.date)}</small><p>${esc(item.text)}</p>${state.letterReplies?.[item.id] ? '<em>已有回信 · 点击查看</em>' : '<em>点击查看信件</em>'}</button>`).join('') : '<p class="couple-empty">信箱还是空的。</p>'}</div>`; }
  function dailyQuestion() { const today = new Date().toISOString().slice(0, 10); if (state.dailyQuestionDate !== today || !state.dailyQuestionText) { let seed = 0; [...today].forEach(char => { seed = (seed * 31 + char.charCodeAt(0)) % 997; }); state.dailyQuestionDate = today; state.dailyQuestionText = questions[seed % questions.length]; save(); } return state.dailyQuestionText; }
  function questionsPage(role, profile) { const question = dailyQuestion(); const answer = state.answers[question] || ''; const roleAnswer = state.roleAnswers?.[question] || ''; return `<article class="couple-question"><h3>${esc(question)}</h3><textarea id="coupleAnswer" placeholder="写下你的答案…">${esc(answer)}</textarea><button class="couple-primary" data-couple-save-answer type="button">保存回答</button>${roleAnswer ? `<div class="couple-answer-thread"><div><span>${esc(profileName(profile))}</span><p>${esc(answer)}</p></div><div><span>${esc(roleName(role))}</span><p>${esc(roleAnswer)}</p></div></div>` : ''}</article>`; }
  function rolePicker() { const { data } = current(); const roleCards = data.contacts.map(item => `<button class="couple-role ${item.id === state.contactId ? 'is-selected' : ''}" data-couple-role="${esc(item.id)}" type="button"><div class="couple-role-avatar">${avatar(item)}</div><span><b>${esc(roleName(item))}</b><small>${data.chats[item.id]?.profileId ? '已绑定用户设定' : '尚未绑定用户设定'}</small></span><i>${item.id === state.contactId ? '✓' : '›'}</i></button>`).join(''); return `<div class="couple-role-sheet"><div class="couple-role-backdrop" data-couple-role-close></div><section><header><h2>选择角色</h2><button data-couple-role-close type="button">×</button></header><div>${roleCards || '<p class="couple-empty">还没有角色，请先在聊天 App 中添加角色。</p>'}</div></section></div>`; }
  function recordOpenMarkup() { if (!recordType) return ''; const labels = { event:['添加纪念日','纪念日名称','日期'], memory:['记录回忆','回忆标题','回忆内容'], wish:['添加共同愿望','愿望内容','备注（可选）'], letter:['写一封信','信件标题','想说的话'] }; const [title, first, second] = labels[recordType]; const dateInput = recordType === 'event' ? '<input id="coupleRecordSecond" type="date">' : `<textarea id="coupleRecordSecond" placeholder="请输入${second}"></textarea>`; return `<div class="couple-record-sheet"><div class="couple-record-backdrop" data-couple-record-close></div><section><header><h2>${title}</h2><button data-couple-record-close type="button">×</button></header><label>${first}<input id="coupleRecordFirst" type="text" placeholder="请输入${first}"></label><label>${second}${dateInput}</label><footer><button data-couple-record-close type="button">取消</button><button data-couple-record-save type="button">保存</button></footer></section></div>`; }
  function letterOpenMarkup() { if (!openLetterId) return ''; const item = state.letters.find(entry => entry.id === openLetterId); if (!item) return ''; const reply = state.letterReplies?.[item.id] || ''; return `<div class="couple-letter-sheet"><div class="couple-letter-backdrop" data-couple-letter-close></div><section><header><div><span>PRIVATE LETTER</span><h2>${esc(item.title)}</h2></div><button data-couple-letter-close type="button">×</button></header><small class="couple-letter-date">${esc(item.date)}</small><p class="couple-letter-content">${esc(item.text)}</p>${reply ? `<div class="couple-letter-reply"><span>角色回信</span><p>${esc(reply)}</p></div>` : '<p class="couple-letter-waiting">这封信还没有收到回信。</p>'}<footer><button data-couple-letter-reply type="button">${reply ? '再次回信' : '让角色回信'}</button></footer></section></div>`; }
  function openPrompt(type) {
    if (type === 'event') { const title = window.prompt('纪念日名称'); if (!title?.trim()) return; const when = window.prompt('日期（例如 2026-08-22）', new Date().toISOString().slice(0, 10)); state.events.unshift({ id: uid('event'), title: title.trim(), date: when?.trim() || date() }); save(); render(); return; }
    if (type === 'wish') { const text = window.prompt('想和对方一起完成什么？'); if (text?.trim()) { state.wishes.unshift({ id: uid('wish'), text: text.trim(), done: false }); save(); render(); } return; }
    if (type === 'letter') { const title = window.prompt('给这封信取个名字', '写给未来的我们'); if (!title?.trim()) return; const text = window.prompt('写下想说的话'); if (text?.trim()) { state.letters.unshift({ id: uid('letter'), title: title.trim(), text: text.trim(), date: date() }); save(); render(); } return; }
    if (type === 'memory') { const title = window.prompt('回忆标题'); if (!title?.trim()) return; const text = window.prompt('写下这段回忆'); if (!text?.trim()) return; pendingMemory = { title: title.trim(), text: text.trim() }; if (window.confirm('要为这段回忆添加一张照片吗？')) app.querySelector('.couple-hidden-file').click(); else finishMemory(''); }
  }
  function finishMemory(image) { if (!pendingMemory) return; state.memories.unshift({ id: uid('memory'), ...pendingMemory, image: image || '', date: date() }); pendingMemory = null; save(); render(); }
  async function generateRoleEvent() { const { role, profile } = current(); const config = window.IdealMachineAPI?.getConfig?.(); const model = window.IdealMachineAPI?.getModel?.('couple'); if (!config?.endpoint || !config.key || !model) return window.alert('请先在设置中为情侣空间配置 API 模型。'); apiBusy = true; render(); try { const response = await fetch(`${config.endpoint.replace(/\/$/, '')}/chat/completions`, { method:'POST', headers:{ 'Content-Type':'application/json', Authorization:`Bearer ${config.key}` }, body:JSON.stringify({ model, temperature:.8, messages:[{ role:'system', content:`你正在扮演角色“${roleName(role)}”。角色设定：${role?.details || role?.signature || '暂无'}\n用户设定：${profile?.persona || '暂无'}` }, { role:'user', content:'请为你们的情侣空间主动想一个值得记录的纪念日。只返回 JSON：{"title":"纪念日名称","date":"YYYY-MM-DD"}。日期必须是有效日期。' }] }) }); if (!response.ok) throw new Error(`HTTP ${response.status}`); const data = await response.json(); const raw = String(data.choices?.[0]?.message?.content || '').replace(/```json|```/gi, '').trim(); const item = JSON.parse(raw); if (!item.title || !/^\d{4}-\d{2}-\d{2}$/.test(item.date)) throw new Error('API 返回的日期格式不正确'); state.events.unshift({ id: uid('event'), title: item.title, date: item.date, author: 'role', authorId: role?.id || '' }); save(); } catch (error) { window.alert(`角色添加纪念日失败：${error.message}`); } finally { apiBusy = false; render(); } }
  async function generateWishResponse(stage, wish) { const { role, profile } = current(); const config = window.IdealMachineAPI?.getConfig?.(); const model = window.IdealMachineAPI?.getModel?.('couple'); if (!config?.endpoint || !config.key || !model) return window.alert('请先在设置中为情侣空间配置 API 模型。'); apiBusy = true; render(); const prompt = stage === 'created' ? `用户刚刚添加了一个共同愿望：“${wish.text}”。请以角色身份回应这份愿望，表现出真实态度或具体计划，回复 1—2 句。` : `用户刚刚完成了共同愿望：“${wish.text}”。请以角色身份写一句有纪念感的回应，回复 1—2 句。`; try { const response = await fetch(`${config.endpoint.replace(/\/$/, '')}/chat/completions`, { method:'POST', headers:{ 'Content-Type':'application/json', Authorization:`Bearer ${config.key}` }, body:JSON.stringify({ model, temperature:.85, messages:[{ role:'system', content:`你正在扮演角色“${roleName(role)}”。角色设定：${role?.details || role?.signature || '暂无'}\n用户设定：${profile?.persona || '暂无'}\n不要解释自己是 AI。` }, { role:'user', content:prompt }] }) }); if (!response.ok) throw new Error(`HTTP ${response.status}`); const data = await response.json(); const text = String(data.choices?.[0]?.message?.content || '').replace(/^['“”"\s]+|['“”"\s]+$/g, '').trim(); if (!text) throw new Error('API 没有返回内容'); state.wishReplies ||= {}; state.wishReplies[wish.id] = text; save(); } catch (error) { window.alert(`角色回应愿望失败：${error.message}`); } finally { apiBusy = false; render(); } }
  async function generateLetterReply() { const letter = state.letters.find(item => item.id === openLetterId); const { role, profile } = current(); if (!letter) return; const config = window.IdealMachineAPI?.getConfig?.(); const model = window.IdealMachineAPI?.getModel?.('couple'); if (!config?.endpoint || !config.key || !model) return window.alert('请先在设置中为情侣空间配置 API 模型。'); apiBusy = true; render(); try { const response = await fetch(`${config.endpoint.replace(/\/$/, '')}/chat/completions`, { method:'POST', headers:{ 'Content-Type':'application/json', Authorization:`Bearer ${config.key}` }, body:JSON.stringify({ model, temperature:.85, messages:[{ role:'system', content:`你正在扮演角色“${roleName(role)}”。角色设定：${role?.details || role?.signature || '暂无'}\n用户设定：${profile?.persona || '暂无'}\n不要解释自己是 AI。` }, { role:'user', content:`用户写给你一封信。标题：${letter.title}\n内容：${letter.text}\n请写一封自然、真诚的回信，控制在 2—4 句。` }] }) }); if (!response.ok) throw new Error(`HTTP ${response.status}`); const data = await response.json(); const text = String(data.choices?.[0]?.message?.content || '').replace(/^['“”"\s]+|['“”"\s]+$/g, '').trim(); if (!text) throw new Error('API 没有返回内容'); state.letterReplies ||= {}; state.letterReplies[letter.id] = text; save(); } catch (error) { window.alert(`角色回信失败：${error.message}`); } finally { apiBusy = false; render(); } }
  async function generateRoleResponse(type, choice) { const { role, profile } = current(); const config = window.IdealMachineAPI?.getConfig?.(); const model = window.IdealMachineAPI?.getModel?.('couple'); if (!config?.endpoint || !config.key || !model) { window.alert('请先在设置中为情侣空间配置 API 模型。'); return; } apiBusy = true; render(); const prompt = type === 'mood' ? `用户刚刚选择了今日心情：“${choice}”。请以角色“${roleName(role)}”的身份自然回应用户，结合角色设定和用户设定，回复 1—2 句，不要解释自己是 AI。` : `用户刚刚对你发起了“${choice}”互动。请以角色“${roleName(role)}”的身份自然回应，结合角色设定和用户设定，回复 1—2 句，不要解释自己是 AI。`; try { const response = await fetch(`${config.endpoint.replace(/\/$/, '')}/chat/completions`, { method:'POST', headers:{ 'Content-Type':'application/json', Authorization:`Bearer ${config.key}` }, body:JSON.stringify({ model, temperature:.85, messages:[{ role:'system', content:`你正在扮演角色“${roleName(role)}”。角色设定：${role?.details || role?.signature || '暂无'}\n用户设定：${profile?.persona || profile?.details || '暂无'}` }, { role:'user', content:prompt }] }) }); if (!response.ok) throw new Error(`HTTP ${response.status}`); const data = await response.json(); const text = String(data.choices?.[0]?.message?.content || '').replace(/^['“”"\s]+|['“”"\s]+$/g, '').trim(); if (!text) throw new Error('API 没有返回内容'); if (type === 'mood') state.moodReply = text; else state.interactionReply = text; save(); } catch (error) { window.alert(`角色回应失败：${error.message}`); } finally { apiBusy = false; render(); } }
  async function generatePageResponse(type) { const { role, profile } = current(); const config = window.IdealMachineAPI?.getConfig?.(); const model = window.IdealMachineAPI?.getModel?.('couple'); if (!config?.endpoint || !config.key || !model) return window.alert('请先在设置中为情侣空间配置 API 模型。'); const content = type === 'calendar' ? state.events.map(item => `${item.title}（${item.date}）`).join('、') || '还没有纪念日' : type === 'memories' ? state.memories.map(item => item.title).join('、') || '还没有回忆' : type === 'wishes' ? state.wishes.map(item => item.text).join('、') || '还没有共同愿望' : state.letters.map(item => item.text).join('、') || '还没有信件'; apiBusy = true; render(); try { const response = await fetch(`${config.endpoint.replace(/\/$/, '')}/chat/completions`, { method:'POST', headers:{ 'Content-Type':'application/json', Authorization:`Bearer ${config.key}` }, body:JSON.stringify({ model, temperature:.85, messages:[{ role:'system', content:`你正在扮演角色“${roleName(role)}”。角色设定：${role?.details || role?.signature || '暂无'}\n用户设定：${profile?.persona || profile?.details || '暂无'}` }, { role:'user', content:`这是情侣空间的${type === 'calendar' ? '共同日历' : type === 'memories' ? '回忆相册' : type === 'wishes' ? '共同愿望' : '情侣信箱'}内容：${content}\n请以角色身份自然回应 1—2 句，不要解释自己是 AI。` }] }) }); if (!response.ok) throw new Error(`HTTP ${response.status}`); const data = await response.json(); const text = String(data.choices?.[0]?.message?.content || '').replace(/^['“”"\s]+|['“”"\s]+$/g, '').trim(); if (!text) throw new Error('API 没有返回内容'); state.roleNotes[type] = text; save(); } catch (error) { window.alert(`角色回应失败：${error.message}`); } finally { apiBusy = false; render(); } }

  document.addEventListener('click', event => {
    if (event.target.closest('[data-app-key="qinglvkongjian"]')) { app.classList.add('is-open'); tab = 'home'; render(); return; }
    if (!app.classList.contains('is-open')) return;
    if (event.target.closest('[data-couple-close]')) { app.classList.remove('is-open'); return; }
    if (event.target.closest('[data-couple-home]')) { tab = 'home'; render(); return; }
    const tabButton = event.target.closest('[data-couple-tab]'); if (tabButton) { tab = tabButton.dataset.coupleTab; render(); return; }
    if (event.target.closest('[data-couple-role-picker]')) { app.querySelector('.couple-page').insertAdjacentHTML('beforeend', rolePicker()); return; }
    const role = event.target.closest('[data-couple-role]'); if (role) { state.contactId = role.dataset.coupleRole; save(); app.querySelector('.couple-role-sheet')?.remove(); render(); return; }
    if (event.target.closest('[data-couple-role-close]')) { app.querySelector('.couple-role-sheet')?.remove(); return; }
    if (event.target.closest('[data-couple-letter-close]')) { openLetterId = ''; render(); return; }
    const letter = event.target.closest('[data-couple-letter]'); if (letter) { openLetterId = letter.dataset.coupleLetter; render(); return; }
    if (event.target.closest('[data-couple-letter-reply]')) { generateLetterReply(); return; }
    const action = event.target.closest('[data-couple-action]'); if (action) { tab = action.dataset.coupleAction === 'mood' ? 'mood' : 'interaction'; render(); return; }
    const mood = event.target.closest('[data-couple-mood]'); if (mood) { state.moods.user = mood.dataset.coupleMood; save(); generateRoleResponse('mood', state.moods.user); return; }
    const interaction = event.target.closest('[data-couple-interaction]'); if (interaction) { state.interaction = interaction.dataset.coupleInteraction; save(); generateRoleResponse('interaction', state.interaction); return; }
    if (event.target.closest('[data-couple-role-add-event]')) { generateRoleEvent(); return; }
    if (event.target.closest('[data-couple-add-event]')) { recordType = 'event'; render(); return; }
    if (event.target.closest('[data-couple-add-memory]')) { recordType = 'memory'; render(); return; }
    if (event.target.closest('[data-couple-add-wish]')) { recordType = 'wish'; render(); return; }
    if (event.target.closest('[data-couple-add-letter]')) { recordType = 'letter'; render(); return; }
    if (event.target.closest('[data-couple-record-close]')) { recordType = ''; render(); return; }
    if (event.target.closest('[data-couple-record-save]')) { const first = app.querySelector('#coupleRecordFirst')?.value.trim(); const second = app.querySelector('#coupleRecordSecond')?.value.trim(); if (!first || !second) return window.alert('请填写完整内容。'); let createdWish = null; if (recordType === 'event') state.events.unshift({ id: uid('event'), title: first, date: second, author: 'user', contactId: current().role?.id || '' }); if (recordType === 'memory') state.memories.unshift({ id: uid('memory'), title: first, text: second, image: '', date: date() }); if (recordType === 'wish') { createdWish = { id: uid('wish'), text: first, note: second, done: false }; state.wishes.unshift(createdWish); } if (recordType === 'letter') state.letters.unshift({ id: uid('letter'), title: first, text: second, date: date() }); recordType = ''; save(); render(); if (createdWish) generateWishResponse('created', createdWish); return; }
    const wish = event.target.closest('[data-couple-toggle-wish]'); if (wish) { const item = state.wishes.find(entry => entry.id === wish.dataset.coupleToggleWish); if (item) { item.done = !item.done; save(); render(); if (item.done) generateWishResponse('completed', item); } return; }
    const delEvent = event.target.closest('[data-couple-delete-event]'); if (delEvent) { state.events = state.events.filter(item => item.id !== delEvent.dataset.coupleDeleteEvent); save(); render(); return; }
    if (event.target.closest('[data-couple-save-answer]')) { const question = dailyQuestion(); const value = app.querySelector('#coupleAnswer')?.value.trim(); if (value) { state.answers[question] = value; state.roleAnswers ||= {}; state.roleAnswers[question] = `我看到你的回答了。${value.length > 12 ? '你的想法我会好好记住。' : '我也这样想。'} 下次我们一起去实现，好吗？`; save(); render(); } return; }
  });
  app.querySelector('.couple-hidden-file').addEventListener('change', event => { const file = event.target.files?.[0]; if (!file) return finishMemory(''); const read = window.IdealMachineReadImage ? window.IdealMachineReadImage(file, 900, .72) : new Promise(resolve => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.readAsDataURL(file); }); read.then(value => finishMemory(value)); event.target.value = ''; });
  window.IdealMachineApps = window.IdealMachineApps || {};
  window.IdealMachineApps.qinglvkongjian = { name: '情侣空间' };
})();
