(() => {
  const key='ideal-machine-music', chatKey='ideal-machine-chat', dbName='ideal-machine-music-files', sessionKey='ideal-machine-netease-session';
  // 与理想机同域部署时保持 '/api'；如果 Worker 是独立域名，可在页面初始化前配置：
  // window.IdealMachineConfig={neteaseApiBase:'https://music-api.example.com'}
  const neteaseApiBase=String(window.IdealMachineConfig?.neteaseApiBase||'https://ideal-music-netease-api.pages.dev/api').replace(/\/$/,'');
  const app=document.createElement('div');app.className='music-app';document.body.appendChild(app);
  const audio=new Audio();audio.preload='auto';audio.playsInline=true;audio.className='music-global-audio';document.body.appendChild(audio);
  let state, page='player', query='', results=[], loading=false, inviteOpen=false, sourceInput='', playing=false, publicLoading=false, loginQr='', loginLoading=false, neteaseProfile=null, selectedPlaylistId='', lyricsFullOpen=false;
  // 公开曲目只在用户主动搜索后载入，不预置在“我的音乐”里。
  let publicTracks=[], lyricRequested=new Set(), lyricLoading=new Set(), queueOpen=false, selectedQueueId='', playMode='list';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const uid=()=>`track-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
  const read=()=>{try{const s=JSON.parse(localStorage.getItem(key)||'{}'),library=s.library||{};Object.keys(library).forEach(id=>{library[id]=Array.isArray(library[id])?library[id].filter(track=>!track?.isPublic&&!['public-william-tell','public-ave-maria'].includes(track?.id)):[];});return {profileId:s.profileId||'',current:s.current||{},rooms:s.rooms||{},library};}catch{return {profileId:'',current:{},rooms:{},library:{}};}};
  const save=()=>localStorage.setItem(key,JSON.stringify(state));
  const profileKey=()=>`ideal-machine-netease-profile-${state?.profileId||'default'}`;
  const readNeteaseProfile=()=>{try{return JSON.parse(localStorage.getItem(profileKey())||'null');}catch{return null;}};
  const saveNeteaseProfile=profile=>{neteaseProfile=profile||null;if(profile)localStorage.setItem(profileKey(),JSON.stringify(profile));else localStorage.removeItem(profileKey());};
  const idb=()=>new Promise((resolve,reject)=>{const r=indexedDB.open(dbName,1);r.onupgradeneeded=()=>r.result.createObjectStore('tracks');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
  const putFile=(id,file)=>idb().then(db=>new Promise((resolve,reject)=>{const r=db.transaction('tracks','readwrite').objectStore('tracks').put(file,id);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error);}));
  const getFile=id=>idb().then(db=>new Promise((resolve,reject)=>{const r=db.transaction('tracks').objectStore('tracks').get(id);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error);}));
  const chat=()=>{try{const s=JSON.parse(localStorage.getItem(chatKey)||'{}');return {profiles:Array.isArray(s.profiles)?s.profiles:[],contacts:Array.isArray(s.contacts)?s.contacts:[],chats:s.chats||{}};}catch{return {profiles:[],contacts:[],chats:{}};}};
  const profile=()=>{const d=chat();if(!state.profileId||!d.profiles.some(x=>x.id===state.profileId))state.profileId=d.profiles[0]?.id||'';return d.profiles.find(x=>x.id===state.profileId)||null;};
  const roles=()=>{const d=chat();return d.contacts.filter(x=>d.chats[x.id]?.profileId===state.profileId);};
  const allRoles=()=>chat().contacts;
  const roleName=id=>{const x=allRoles().find(v=>v.id===id);return x?.nickname||x?.name||'角色';};
  const avatar=x=>x?.avatar?`<img src="${esc(x.avatar)}" alt="">`:esc((x?.nickname||x?.name||'♪').slice(0,1));
  const library=()=>state.library[state.profileId] ||= [];
  const current=()=>state.current[state.profileId]||null;
  const room=()=>state.rooms[state.profileId]||null;
  const icons={search:'<circle cx="21" cy="21" r="10"/><path d="m29 29 10 10"/>',close:'<path d="m15 15 18 18M33 15 15 33"/>',play:'<path d="m18 12 19 12-19 12z"/>',pause:'<path d="M18 13v22M30 13v22"/>',prev:'<path d="M32 13 18 24l14 11zM14 13v22"/>',next:'<path d="M16 13 30 24 16 35zM34 13v22"/>',queue:'<path d="M11 14h22M11 24h22M11 34h14"/>',music:'<path d="M31 10v22a6 6 0 1 1-3-5.2V16l-14 3v16a6 6 0 1 1-3-5.2V15z"/>',users:'<circle cx="17" cy="18" r="6"/><circle cx="33" cy="19" r="5"/><path d="M7 39c1-8 5-11 10-11s9 3 10 11M28 29c6 0 10 3 11 9"/>',user:'<circle cx="24" cy="16" r="7"/><path d="M11 39c1-8 5-11 13-11s12 3 13 11"/>',link:'<path d="M20 28 28 20M18 34l-3 3a7 7 0 0 1-10-10l7-7a7 7 0 0 1 10 0M30 14l3-3a7 7 0 0 1 10 10l-7 7a7 7 0 0 1-10 0"/>'};
  const svg=t=>`<svg viewBox="0 0 48 48">${icons[t]||''}</svg>`;
  icons.shuffle='<path d="M8 12h5c5 0 7 24 14 24h5M32 12h-5c-7 0-9 24-14 24H8M28 9l4 3-4 3M28 33l4 3-4 3"/>';
  icons.repeat='<path d="M10 17h22l-4-4M38 31H16l4 4M10 17v7M38 24v7"/>';
  icons.repeatOne='<path d="M10 17h22l-4-4M38 31H16l4 4M10 17v7M38 24v7"/><path d="M24 19v8l-2-2"/>';
  const cover=s=>s.cover?`<img src="${esc(s.cover)}" alt="">`:svg('music');
  const roomStrip=()=>{const r=room(),s=current();if(!r||r.song.id!==s?.id)return '';return `<section class="music-room"><div class="music-room-art">${cover(s)}</div><div class="music-room-copy"><span>LISTENING TOGETHER</span><b>正在和 ${esc(roleName(r.roleId))} 一起听</b><small>${esc(s.title)} · ${esc(s.artist)}</small></div><button data-music-invite type="button">更换</button></section>`;};
  const lyricLines=s=>{if(Array.isArray(s?.lyrics))return s.lyrics;const raw=typeof s?.lyric==='string'?s.lyric:'';return raw.split(/\r?\n/).flatMap(row=>{const match=row.match(/^\[(\d+):(\d+(?:\.\d+)?)\](.*)$/);return match?[{time:Number(match[1])*60+Number(match[2]),text:match[3].trim()}]:row.trim()?[{time:0,text:row.trim()}]:[];});};
  const lyricsPanel=s=>{const lines=lyricLines(s),placeholder=lyricLoading.has(s?.id)?'正在同步歌词…':'暂无歌词';return `<section class="music-lyrics" aria-label="歌词"><div class="music-lyrics-window">${lines.length?lines.map((line,index)=>`<p data-music-lyric-line="${index}" data-lyric-time="${Number(line.time)||0}">${esc(line.text||'')}</p>`).join(''):`<p class="is-placeholder">${placeholder}</p>`}</div></section>`;};
  const fullLyricsPage=s=>{const lines=lyricLines(s),placeholder=lyricLoading.has(s?.id)?'正在同步歌词…':'暂无歌词';return `<section class="music-full-lyrics-page"><div class="music-full-lyrics-bg">${s.cover?`<img src="${esc(s.cover)}" alt="">`:''}</div><header class="music-full-lyrics-header"><button data-music-lyrics-back type="button" aria-label="返回播放器">‹</button><div><b>歌词</b><small>${esc(s.title)} · ${esc(s.artist||'网易云音乐')}</small></div><button data-music-close type="button" aria-label="关闭音乐">${svg('close')}</button></header><main class="music-full-lyrics-main"><div class="music-full-lyrics-art">${cover(s)}</div><div class="music-full-lyrics-scroll" aria-label="完整歌词">${lines.length?lines.map((line,index)=>`<p data-music-lyric-line="${index}" data-lyric-time="${Number(line.time)||0}">${esc(line.text||'')}</p>`).join(''):`<p class="is-placeholder">${placeholder}</p>`}</div></main><footer class="music-full-lyrics-controls"><button data-music-prev type="button" aria-label="上一首">${svg('prev')}</button><button class="is-primary" data-music-toggle type="button" aria-label="${playing?'暂停':'播放'}">${svg(playing?'pause':'play')}</button><button data-music-next type="button" aria-label="下一首">${svg('next')}</button></footer></section>`;};
  const queuePanel=()=>{const lists=neteaseProfile?.playlists||[],active=lists.find(list=>list.id===selectedQueueId)||lists[0],tracks=active?.tracks||[];return queueOpen?`<section class="music-queue-panel"><header><select data-music-queue-select aria-label="选择歌单">${lists.length?lists.map(list=>`<option value="${esc(list.id)}" ${list.id===active?.id?'selected':''}>${esc(list.name)}</option>`).join(''):'<option>暂无歌单</option>'}</select><button data-music-queue-close type="button">${svg('close')}</button></header>${tracks.length?tracks.map((song,index)=>`<button class="music-queue-song ${song.id===current()?.id?'is-current':''}" data-music-queue-song="${esc(song.id)}" type="button"><em>${index+1}</em><span><b>${esc(song.title)}</b><small>${esc(song.artist||'网易云音乐')}</small></span><i>${svg('play')}</i></button>`).join(''):'<p class="music-empty">这个歌单暂时没有歌曲。</p>'}</section>`:'';};
  function player(){const s=current(),r=room();if(!s)return `<section class="music-player-empty"><i>${svg('music')}</i><h2>还没有正在播放的音乐</h2><p>到“我的”导入本地音乐或添加你有授权的音频链接。</p><button data-music-page="my" type="button">打开我的音乐</button></section>`;return `<section class="music-player"><button class="music-disc ${playing?'is-playing':''}" data-music-open-lyrics type="button" aria-label="打开完整歌词"><div>${cover(s)}</div></button><div class="music-player-meta"><h2>${esc(s.title)}</h2><p>${esc(s.artist||'本地音乐')}</p></div><div class="music-progress"><div class="music-progress-times"><span data-music-time-current>0:00</span><span data-music-time-total>0:00</span></div><input data-music-progress type="range" min="0" max="0" step="0.1" value="0" aria-label="播放进度"></div><div class="music-player-controls"><button data-music-prev type="button" aria-label="上一首">${svg('prev')}</button><button class="music-play-control" data-music-toggle type="button" aria-label="${playing?'暂停':'播放'}">${svg(playing?'pause':'play')}</button><button data-music-next type="button" aria-label="下一首">${svg('next')}</button><button class="music-queue-button" data-music-queue type="button" aria-label="歌单">${svg('queue')}</button></div>${queuePanel()}${lyricsPanel(s)}${s.source==='search'?'<small class="music-preview-note">公开试听片段</small>':''}<section class="music-together ${r?.song.id===s.id?'is-active':''}"><div><span>${r?.song.id===s.id?'LISTENING TOGETHER':'LISTEN TOGETHER'}</span><b>${r?.song.id===s.id?`正在和 ${esc(roleName(r.roleId))} 一起听`:'邀请角色一起听'}</b><small>角色会同步看到歌曲与一起听状态。</small></div><button data-music-invite type="button">${svg('users')} ${r?.song.id===s.id?'更换':'邀请'}</button></section></section>`;}
  function search(){return `<section class="music-search"><svg viewBox="0 0 48 48">${icons.search}</svg><input data-music-query value="${esc(query)}" placeholder="搜索网易云歌曲、歌手或专辑"><button data-music-search type="button">搜索</button></section>${loading?'<div class="music-status">正在搜索网易云音乐…</div>':''}${results.length?`<section class="music-results">${results.map(s=>`<article class="music-song"><div class="music-cover">${cover(s)}</div><div><b>${esc(s.title)}</b><small>${esc(s.artist)}${s.album?` · ${esc(s.album)}`:''}</small></div><button data-music-select="${esc(s.id)}" type="button">${svg('play')}</button></article>`).join('')}</section>`:!loading?'<div class="music-empty">输入歌名、歌手或专辑，结果来自网易云音乐。</div>':''}`;}
  function mine(){const list=library();const p=neteaseProfile;return `${p?`<section class="music-netease-profile"><div class="music-netease-avatar">${p.avatarUrl?`<img src="${esc(p.avatarUrl)}" alt="">`:esc((p.nickname||'云').slice(0,1))}</div><div><span>NETEASE CLOUD MUSIC</span><b>${esc(p.nickname||p.userName||'网易云用户')}</b><small>${esc(p.signature||'网易云音乐个人主页已同步')}</small></div><button data-music-profile-refresh type="button">同步</button></section>`:`<section class="music-provider-login"><div class="music-provider-mark"><i></i><i></i><i></i></div><div class="music-provider-copy"><span>NETEASE CLOUD MUSIC</span><b>网易云音乐登录</b><small>${loginLoading?'正在获取二维码，请稍候…':'登录后可同步你的音乐服务。'}</small></div><button data-music-netease-login type="button" ${loginLoading?'disabled':''}>${loginLoading?'正在连接…':'二维码登录'}</button></section>`}${loginQr?`<section class="music-qr-panel"><img src="${esc(loginQr)}" alt="网易云登录二维码"><p>请使用网易云音乐 App 扫码登录</p></section>`:''}<section class="music-import-actions"><button data-music-import type="button">${svg('music')} 导入本地音乐</button><input data-music-file type="file" accept="audio/*,.flac" multiple hidden></section><section class="music-url-import"><input data-music-url value="${esc(sourceInput)}" placeholder="粘贴 MP3、M4A 等音频链接"><button data-music-add-url type="button">添加</button></section><section class="music-library-list">${list.length?list.map(s=>`<article class="music-song"><div class="music-cover">${cover(s)}</div><div><b>${esc(s.title)}</b><small>${esc(s.artist||'我的音乐库')} · ${s.source==='file'?'本地文件':'授权链接'}</small></div><button data-music-library-play="${esc(s.id)}" type="button">${svg('play')}</button></article>`).join(''):'<div class="music-empty">还没有音乐。导入后可以完整播放并邀请角色一起听。</div>'}</section>`;}
  function tabs(){return `<nav class="music-tabs"><button class="${page==='player'?'is-active':''}" data-music-page="player" type="button">${svg('music')}<small>播放</small></button><button class="${page==='search'?'is-active':''}" data-music-page="search" type="button">${svg('search')}<small>搜索</small></button><button class="${page==='my'?'is-active':''}" data-music-page="my" type="button">${svg('user')}<small>我的</small></button></nav>`;}
  function sheet(){const s=current(),list=allRoles();return `<div class="music-sheet"><div class="music-sheet-mask" data-music-invite-close></div><section><header><div><span>INVITE</span><h2>邀请一起听</h2></div><button data-music-invite-close type="button">${svg('close')}</button></header><div class="music-invite-song"><div>${cover(s)}</div><span><b>${esc(s?.title||'')}</b><small>${esc(s?.artist||'')}</small></span></div><p>所有已创建的角色都可以邀请。</p><div class="music-role-list">${list.length?list.map(r=>`<button data-music-role="${esc(r.id)}" type="button"><i>${avatar(r)}</i><span><b>${esc(r.nickname||r.name)}</b><small>${esc(r.identity||'角色')}</small></span><em>邀请</em></button>`).join(''):'<div class="music-empty">当前还没有创建角色。</div>'}</div></section></div>`;}
  function render(){const p=profile(),song=current();if(p&&page==='player'&&lyricsFullOpen&&song){app.innerHTML=fullLyricsPage(song);return;}app.innerHTML=`<section class="music-page"><header class="music-header"><div><span>MUSIC</span><h1>${page==='search'?'搜索音乐':page==='my'?'我的音乐':'音乐播放'}</h1></div><button data-music-close type="button">${svg('close')}</button></header><main class="music-main">${p?(page==='search'?search():page==='my'?mine():player()):'<div class="music-empty">请先在聊天 App 的“我”页面创建用户设定。</div>'}</main>${tabs()}${inviteOpen?sheet():''}</section>`;}
  async function api(path,options){const headers={accept:'application/json',...(options?.headers||{})},session=localStorage.getItem(sessionKey),publicQr=/^\/auth\/qr\//.test(path);if(session&&!publicQr)headers.authorization=`Bearer ${session}`;const response=await fetch(`${neteaseApiBase}${path}`,{...options,credentials:'omit',cache:'no-store',headers});let data=null;try{data=await response.json();}catch{}if(!response.ok)throw new Error(data?.error||`API ${response.status}`);return data;}
  async function activate(song){let playUrl=song.playUrl||song.preview||song.url||'';try{if(song.source==='file'){const blob=await getFile(song.id);if(!blob)return window.alert('找不到本地音频文件，请重新导入。');playUrl=URL.createObjectURL(blob);}else if(song.source==='netease'&&!playUrl){const data=await api(`/song/${encodeURIComponent(song.id)}/url?br=320000`);playUrl=data?.data?.[0]?.url||data?.[0]?.url||data?.data?.url||data?.url||'';if(!playUrl)return window.alert('当前歌曲没有可用播放地址，请检查网易云账号权限或接口配置。');}}catch(error){return window.alert(`网易云音乐连接失败：${error.message}`);}if(song.source==='netease'&&!song.lyric)lyricRequested.delete(song.id);state.current[state.profileId]={...song,playUrl};if(room()?.song.id!==song.id)delete state.rooms[state.profileId];save();audio.pause();audio.src='';audio.load();audio.src=playUrl;audio.load();audio.currentTime=0;page='player';render();loadLyrics(state.current[state.profileId]);audio.play().catch(()=>{playing=false;render();window.alert('当前歌曲播放失败，请检查音源是否可用，或点击播放键重试。');});}
  const playbackQueue=()=>{const song=current(),playlists=neteaseProfile?.playlists||[],playlist=playlists.find(list=>list.id===selectedQueueId)||playlists.find(list=>list.tracks?.some(item=>String(item.id)===String(song?.id))),items=playlist?.tracks?.map(item=>({...item,source:'netease'}))||[...library(),...results],seen=new Set();return items.filter(item=>item?.id&&!seen.has(String(item.id))&&(seen.add(String(item.id)),true));};
  function changeTrack(step){const queue=playbackQueue(),song=current(),index=queue.findIndex(item=>String(item.id)===String(song?.id));if(!queue.length||index<0)return window.alert('当前没有可切换的歌曲。');const next=playMode==='shuffle'?queue[Math.floor(Math.random()*queue.length)]:queue[(index+step+queue.length)%queue.length];activate(next);}
  const modeIcon=()=>playMode==='shuffle'?'shuffle':playMode==='one'?'repeatOne':'repeat';
  const modeLabel=()=>playMode==='shuffle'?'随机播放':playMode==='one'?'单曲循环':'列表循环';
  function cyclePlayMode(){playMode=playMode==='list'?'shuffle':playMode==='shuffle'?'one':'list';render();}
  async function restoreCurrent(){const song=current();if(!song)return;const knownUrl=song.playUrl||song.preview||song.url||'';if(audio.src&&knownUrl&&audio.src===knownUrl)return;try{if(song.source==='file'){const blob=await getFile(song.id);if(blob){const playUrl=URL.createObjectURL(blob);if(audio.src&&audio.src===song.playUrl)return;state.current[state.profileId]={...song,playUrl};audio.src=playUrl;save();}}else if(knownUrl&&!audio.src){audio.src=knownUrl;}}catch{}}
  function deezer(term){return new Promise((resolve,reject)=>{const cb=`idealMusic${Date.now()}${Math.random().toString(36).slice(2)}`,script=document.createElement('script'),timer=setTimeout(()=>{delete window[cb];script.remove();reject();},15000);window[cb]=d=>{clearTimeout(timer);delete window[cb];script.remove();resolve(d);};script.onerror=()=>{clearTimeout(timer);delete window[cb];script.remove();reject();};script.src=`https://api.deezer.com/search?q=${encodeURIComponent(term)}&limit=24&output=jsonp&callback=${cb}`;document.head.appendChild(script);});}
  async function doSearch(){const term=query.trim();if(!term)return;loading=true;results=[];render();try{const data=await api(`/search?keywords=${encodeURIComponent(term)}&limit=24&type=1`),songs=data?.result?.songs||data?.songs||[];results=songs.map(x=>{const artists=x.ar||x.artists||[],album=x.al||x.album||{};return {id:String(x.id),title:x.name||'',artist:artists.map(a=>a.name).join(' / '),album:album.name||'',cover:album.picUrl||'',source:'netease'};});if(!results.length)window.alert('网易云音乐没有找到相关歌曲。');}catch(error){window.alert(`网易云音乐搜索失败：${error.message}`);}finally{loading=false;render();}}
  async function syncNeteaseProfile(){const data=await api('/user/sync');const profile=data?.profile||{},account=data?.account?.account||data?.account||{},vip=data?.vip?.data||data?.vip||{};const playlists=Array.isArray(data?.playlists)?data.playlists:[];const music=playlists.flatMap(list=>Array.isArray(list.tracks)?list.tracks.map(song=>({id:String(song.id||''),title:song.name||'未命名歌曲',artist:song.ar?.map?.(x=>x.name).join(' / ')||song.artist||'',cover:song.al?.picUrl||song.picUrl||''})):[]).filter(song=>song.id);const vipType=profile.vipType??account.vipType??vip.vipType??vip.type??0;const normalized={userId:String(data?.userId||profile.userId||account.id||''),nickname:profile.nickname||account.nickname||'网易云用户',avatarUrl:profile.avatarUrl||account.avatarUrl||'',signature:profile.signature||profile.description||'',level:profile.level||profile.levelInfo?.level||'',vip:Boolean(profile.isVip||profile.vip||account.isVip||vip.isVip||Number(vipType)>0),vipLabel:profile.vipLabel||vip.label||(Number(vipType)>0?'VIP':'普通用户'),music,playlists:playlists.map(list=>({id:String(list.id||''),name:list.name||'未命名歌单',cover:list.coverImgUrl||list.cover||'',trackCount:Number(list.trackCount||list.size||list.tracks?.length||0),tracks:(list.tracks||[]).map(song=>({id:String(song.id||''),title:song.name||'未命名歌曲',artist:song.ar?.map?.(x=>x.name).join(' / ')||song.artist||'',cover:song.al?.picUrl||song.picUrl||''}))}))};saveNeteaseProfile(normalized);render();return normalized;}
  async function neteaseLogin(){if(loginLoading)return;loginLoading=true;loginQr='';render();try{const keyData=await api('/auth/qr/key');const key=keyData?.data?.unikey||keyData?.unikey;if(!key)throw new Error('无法获取登录二维码');const qr=await api(`/auth/qr/create?key=${encodeURIComponent(key)}`);const image=qr?.data?.qrimg||qr?.qrimg;if(!image)throw new Error('无法生成登录二维码');loginQr=`${neteaseApiBase}/auth/qr/image?key=${encodeURIComponent(key)}&timestamp=${Date.now()}`;loginLoading=false;render();const check=async()=>{const status=await api(`/auth/qr/check?key=${encodeURIComponent(key)}`);if(status?.sessionToken){localStorage.setItem(sessionKey,status.sessionToken);loginQr='';try{await syncNeteaseProfile();lyricRequested.clear();lyricLoading.clear();loadLyrics(current());window.alert('网易云音乐登录成功，个人页面已同步。');}catch(error){window.alert(`登录成功，但个人页面同步失败：${error.message}`);}render();return;}if(status?.code===803||status?.data?.code===803){loginQr='';render();window.alert('网易云已确认登录，但会话创建失败，请重新扫码。');return;}if(status?.code===800||status?.data?.code===800){loginQr='';window.alert('二维码已过期，请重新登录。');render();return;}setTimeout(check,2000);};check();}catch(error){loginQr='';loginLoading=false;render();window.alert(`网易云登录失败：${error.message}`);}}
  async function logoutNetease(){try{await api('/auth/logout',{method:'POST'});}catch{}localStorage.removeItem(sessionKey);saveNeteaseProfile(null);loginQr='';loginLoading=false;render();window.alert('已彻底退出网易云音乐账号。');}
  async function importFiles(files){const entries=Array.from(files||[]).filter(f=>f.type.startsWith('audio/')||/\.(mp3|m4a|aac|wav|flac|ogg)$/i.test(f.name));if(!entries.length)return;for(const file of entries){const title=file.name.replace(/\.[^.]+$/,'');const track={id:uid(),title,artist:'本地音乐',source:'file'};await putFile(track.id,file);library().push(track);}save();page='my';render();}
  function addUrl(){const url=sourceInput.trim();if(!/^https:\/\//i.test(url))return window.alert('请输入 https 音频链接。');const title=url.split('/').pop().split('?')[0]||'授权音频';library().push({id:uid(),title,artist:'授权音频链接',source:'url',url,playUrl:url});sourceInput='';save();render();}
  async function loadPublicCatalog(){if(publicLoading||publicTracks.some(song=>song.id.startsWith('archive-chopin-')))return;publicLoading=true;try{const response=await fetch('https://archive.org/metadata/musopen-chopin');if(!response.ok)throw new Error('catalog');const data=await response.json();const files=(data.files||[]).filter(file=>/\.mp3$/i.test(file.name||'')).slice(0,80);if(files.length)publicTracks=files.map(file=>{const url=`https://archive.org/download/musopen-chopin/${encodeURIComponent(file.name)}`;return {id:`archive-chopin-${file.name}`,title:String(file.name).replace(/\.mp3$/i,''),artist:'Frédéric Chopin · Musopen',source:'url',url,playUrl:url,isPublic:true};});}finally{publicLoading=false;}}
  document.addEventListener('click',e=>{if(e.target.closest('[data-app-key="yinyue"]')){state=read();profile();save();neteaseProfile=readNeteaseProfile();page=current()?'player':'my';query='';results=[];selectedPlaylistId='';inviteOpen=false;playing=!audio.paused;app.classList.add('is-open');lyricRequested.clear();lyricLoading.clear();render();loadLyrics(current());restoreCurrent().then(()=>{render();loadLyrics(current());});return;}if(!app.classList.contains('is-open'))return;if(e.target.closest('[data-music-close]')){app.classList.remove('is-open');return;}if(e.target.closest('[data-music-toggle]')){if(audio.paused)audio.play().catch(()=>window.alert('当前音频无法播放，请检查文件或链接。'));else audio.pause();return;}const pg=e.target.closest('[data-music-page]');if(pg){page=pg.dataset.musicPage;render();return;}if(e.target.closest('[data-music-search]')){doSearch();return;}if(e.target.closest('[data-music-import]')){app.querySelector('[data-music-file]')?.click();return;}if(e.target.closest('[data-music-add-url]')){addUrl();return;}if(e.target.closest('[data-music-netease-login]')){neteaseLogin();return;}if(e.target.closest('[data-music-profile-refresh]')){syncNeteaseProfile().catch(error=>window.alert(`个人页面同步失败：${error.message}`));return;}const chosen=e.target.closest('[data-music-select]');if(chosen){const s=results.find(x=>x.id===chosen.dataset.musicSelect);if(s)activate(s);return;}const local=e.target.closest('[data-music-library-play]');if(local){const s=library().find(x=>x.id===local.dataset.musicLibraryPlay);if(s)activate(s);return;}if(e.target.closest('[data-music-invite]')){if(!current())return;inviteOpen=true;render();return;}if(e.target.closest('[data-music-invite-close]')){inviteOpen=false;render();return;}const role=e.target.closest('[data-music-role]');if(role){state.rooms[state.profileId]={song:current(),roleId:role.dataset.musicRole,startedAt:Date.now()};save();inviteOpen=false;render();}});
  document.addEventListener('click',e=>{if(e.target.closest('[data-app-key="yinyue"]')){lyricsFullOpen=false;if(app.classList.contains('is-open')){render();updateProgress();}return;}if(e.target.closest('[data-music-close]')){lyricsFullOpen=false;return;}if(!app.classList.contains('is-open'))return;if(e.target.closest('[data-music-page]')){lyricsFullOpen=false;if(page==='player')updateProgress();return;}if(e.target.closest('[data-music-open-lyrics]')){lyricsFullOpen=true;render();loadLyrics(current());updateProgress();return;}if(e.target.closest('[data-music-lyrics-back]')){lyricsFullOpen=false;render();updateProgress();return;}});
  document.addEventListener('input',e=>{if(!app.classList.contains('is-open'))return;if(e.target.matches('[data-music-query]'))query=e.target.value;if(e.target.matches('[data-music-url]'))sourceInput=e.target.value;});
  document.addEventListener('change',e=>{if(app.classList.contains('is-open')&&e.target.matches('[data-music-file]'))importFiles(e.target.files);});
  document.addEventListener('keydown',e=>{if(app.classList.contains('is-open')&&e.key==='Enter'&&e.target.matches('[data-music-query]'))doSearch();});
  audio.addEventListener('play',()=>{playing=true;if(app.classList.contains('is-open')&&page==='player'){render();updateProgress();}});
  audio.addEventListener('pause',()=>{playing=false;if(app.classList.contains('is-open')&&page==='player'){render();updateProgress();}});
  audio.addEventListener('ended',()=>{playing=false;if(app.classList.contains('is-open')&&page==='player'){render();updateProgress();}});
  document.addEventListener('click',e=>{if(!app.classList.contains('is-open'))return;if(e.target.closest('[data-music-mode]')){cyclePlayMode();return;}if(e.target.closest('[data-music-prev]')){changeTrack(-1);return;}if(e.target.closest('[data-music-next]')){changeTrack(1);return;}if(e.target.closest('[data-music-queue]')){const first=neteaseProfile?.playlists?.[0];if(!selectedQueueId&&first)selectedQueueId=first.id;queueOpen=!queueOpen;render();return;}if(e.target.closest('[data-music-queue-close]')){queueOpen=false;render();return;}const song=e.target.closest('[data-music-queue-song]');if(song){const list=neteaseProfile?.playlists?.find(item=>item.id===selectedQueueId),track=list?.tracks?.find(item=>item.id===song.dataset.musicQueueSong);if(track)activate({...track,source:'netease'});return;}});
  document.addEventListener('change',e=>{if(!app.classList.contains('is-open')||!e.target.matches('[data-music-queue-select]'))return;selectedQueueId=e.target.value;render();});
  document.addEventListener('input',e=>{if(!app.classList.contains('is-open')||!e.target.matches('[data-music-progress]')||!Number.isFinite(audio.duration))return;audio.currentTime=Number(e.target.value);updateProgress();});
  audio.addEventListener('loadedmetadata',()=>{updateProgress();loadLyrics(current());});audio.addEventListener('timeupdate',updateProgress);audio.addEventListener('ended',()=>{if(playMode==='one'){audio.currentTime=0;audio.play().catch(()=>{});return;}const queue=playbackQueue(),index=queue.findIndex(item=>String(item.id)===String(current()?.id));if(queue.length>1&&index>=0)changeTrack(1);});
  function clock(value){if(!Number.isFinite(value)||value<0)return '0:00';const minutes=Math.floor(value/60),seconds=Math.floor(value%60);return `${minutes}:${String(seconds).padStart(2,'0')}`;}
  async function loadLyrics(song){if(!song||song.source!=='netease'||song.lyric||lyricRequested.has(song.id))return;lyricRequested.add(song.id);lyricLoading.add(song.id);if(current()?.id===song.id&&app.classList.contains('is-open'))render();try{const data=await api(`/lyric/${encodeURIComponent(song.id)}`),lyric=data?.lrc?.lyric||data?.lyric||'';if(lyric&&current()?.id===song.id){state.current[state.profileId]={...current(),lyric};save();}}catch{lyricRequested.delete(song.id);}finally{lyricLoading.delete(song.id);if(current()?.id===song.id&&app.classList.contains('is-open')){render();updateProgress();}}}
  function updateLyrics(){const lines=[...app.querySelectorAll('[data-music-lyric-line]')];if(!lines.length)return;let active=0,changed=false;lines.forEach((line,index)=>{if(Number(line.dataset.lyricTime)<=audio.currentTime)active=index;});lines.forEach((line,index)=>{const shouldBeActive=index===active;if(shouldBeActive&&!line.classList.contains('is-active'))changed=true;line.classList.toggle('is-active',shouldBeActive);});const scroller=app.querySelector('.music-full-lyrics-scroll'),activeLine=lines[active];if(changed&&scroller&&activeLine){const lineRect=activeLine.getBoundingClientRect(),scrollRect=scroller.getBoundingClientRect(),top=scroller.scrollTop+lineRect.top-scrollRect.top-(scroller.clientHeight-lineRect.height)/2;scroller.scrollTo({top:Math.max(0,top),behavior:'smooth'});}}
  function updateProgress(){if(!app.classList.contains('is-open')||page!=='player')return;const range=app.querySelector('[data-music-progress]');if(range){range.max=Number.isFinite(audio.duration)?audio.duration:0;range.value=Number.isFinite(audio.currentTime)?audio.currentTime:0;range.style.setProperty('--music-progress',`${audio.duration?audio.currentTime/audio.duration*100:0}%`);}const currentTime=app.querySelector('[data-music-time-current]'),totalTime=app.querySelector('[data-music-time-total]');if(currentTime)currentTime.textContent=clock(audio.currentTime);if(totalTime)totalTime.textContent=clock(audio.duration);updateLyrics();}
  const neteaseAccountCard=p=>`<section class="music-netease-account"><div class="music-netease-account-head"><div class="music-netease-avatar">${p.avatarUrl?`<img src="${esc(p.avatarUrl)}" alt="">`:esc((p.nickname||'云').slice(0,1))}</div><div><span>NETEASE CLOUD MUSIC</span><b>${esc(p.nickname||'网易云用户')}</b><small>${esc(p.signature||'网易云音乐个人主页已同步')}</small></div><em class="${p.vip?'is-vip':''}">${esc(p.vipLabel||'普通用户')}</em></div><div class="music-netease-account-meta"><span>歌单歌曲 <b>${p.music?.length||0}</b></span><span>账号等级 <b>${esc(p.level||'—')}</b></span></div><div class="music-netease-account-actions"><button data-music-profile-refresh type="button">同步个人页</button><button data-music-netease-logout type="button">退出登录</button></div></section>`;
  function decorateNeteasePlaylists(){if(page!=='my'||!neteaseProfile?.playlists?.length)return;const card=app.querySelector('.music-netease-account');if(!card||card.querySelector('.music-netease-playlists'))return;const panel=document.createElement('div');panel.className='music-netease-playlists';const selected=neteaseProfile.playlists.find(list=>list.id===selectedPlaylistId);panel.innerHTML=selected?`<div class="music-netease-playlists-title"><button class="music-playlist-back" data-music-playlist-back type="button">‹ 返回歌单</button><span>${esc(selected.name)} · ${selected.tracks?.length||0} 首</span></div><div class="music-playlist-tracks">${selected.tracks?.length?selected.tracks.map(song=>`<article class="music-song"><div class="music-cover">${cover(song)}</div><div><b>${esc(song.title)}</b><small>${esc(song.artist||'网易云音乐')}</small></div><button data-music-playlist-song="${esc(song.id)}" type="button">${svg('play')}</button></article>`).join(''):'<div class="music-empty">这个歌单暂时没有可播放歌曲。</div>'}</div>`:`<div class="music-netease-playlists-title">我的歌单 <span>${neteaseProfile.playlists.length} 个</span></div>${neteaseProfile.playlists.slice(0,20).map(list=>`<button class="music-netease-playlist" data-music-playlist="${esc(list.id)}" type="button"><div>${list.cover?`<img src="${esc(list.cover)}" alt="">`:svg('music')}</div><span><b>${esc(list.name)}</b><small>${list.trackCount?`${list.trackCount} 首歌曲`:'网易云歌单'}</small></span><em>›</em></button>`).join('')}`;const actions=card.querySelector('.music-netease-account-actions');card.insertBefore(panel,actions);}
  function decorateListeningTogether(){const box=app.querySelector('.music-together');if(!box||box.querySelector('.music-together-people'))return;const r=room(),active=Boolean(r?.song?.id&&r.song.id===current()?.id),me=neteaseProfile?.avatarUrl?`<img src="${esc(neteaseProfile.avatarUrl)}" alt="用户">`:avatar(profile());const role=allRoles().find(item=>item.id===r?.roleId);const other=role?avatar(role):svg('user');const people=document.createElement('div');people.className='music-together-people';people.innerHTML=`<div class="music-together-person"><i>${me}</i><small>我</small></div><span class="music-together-link" aria-label="跳动爱心"><svg viewBox="0 0 58 24" aria-hidden="true"><path class="heartbeat-line" d="M1 12h10l3-7 5 14 5-11 4 4h29"/></svg><span>♥</span></span><div class="music-together-person music-together-role-pick" data-music-invite><i>${other}</i><small>${active?esc(role?.nickname||role?.name||'角色'):'邀请角色'}</small></div>`;const title=box.querySelector('b');if(title)title.textContent=active?`正在和 ${roleName(r.roleId)} 听歌`:'邀请角色一起听';box.prepend(people);}
  function decoratePlaybackControls(){const controls=app.querySelector('.music-player-controls');if(!controls||controls.querySelector('[data-music-mode]'))return;const button=document.createElement('button');button.dataset.musicMode='';button.type='button';button.title=modeLabel();button.setAttribute('aria-label',modeLabel());button.innerHTML=svg(modeIcon());controls.insertBefore(button,controls.querySelector('[data-music-prev]'));}
  function placeLyricsBetween(){const lyrics=app.querySelector('.music-lyrics'),controls=app.querySelector('.music-player-controls'),together=app.querySelector('.music-together');if(!lyrics||!controls||!together)return;const controlsRect=controls.getBoundingClientRect(),togetherRect=together.getBoundingClientRect();if(togetherRect.top>controlsRect.bottom){lyrics.style.left='50%';lyrics.style.top=`${controlsRect.bottom+(togetherRect.top-controlsRect.bottom)/2}px`;}}
  function decorateNeteasePanel(){if(page==='my'&&neteaseProfile){const panel=app.querySelector('.music-netease-profile');if(panel&&!app.querySelector('.music-netease-account'))panel.outerHTML=neteaseAccountCard(neteaseProfile);decorateNeteasePlaylists();}decoratePlaybackControls();decorateListeningTogether();placeLyricsBetween();requestAnimationFrame(()=>requestAnimationFrame(placeLyricsBetween));}
  new MutationObserver(decorateNeteasePanel).observe(app,{childList:true,subtree:true});
  document.addEventListener('click',e=>{if(!app.classList.contains('is-open'))return;if(e.target.closest('[data-music-netease-logout]')){logoutNetease();return;}const playlist=e.target.closest('[data-music-playlist]');if(playlist){selectedPlaylistId=playlist.dataset.musicPlaylist;render();return;}if(e.target.closest('[data-music-playlist-back]')){selectedPlaylistId='';render();return;}const songButton=e.target.closest('[data-music-playlist-song]');if(songButton){const selected=neteaseProfile?.playlists?.find(list=>list.id===selectedPlaylistId),song=selected?.tracks?.find(item=>item.id===songButton.dataset.musicPlaylistSong);if(song){selectedQueueId=selectedPlaylistId;activate({...song,source:'netease'});}return;}});
  window.addEventListener('resize',placeLyricsBetween);window.IdealMachineApps=window.IdealMachineApps||{};window.IdealMachineApps.yinyue={name:'音乐'};
})();
